### ISSUE TITLE
Expected int32 passed to parameter 'size' of op 'ResizeBilinear', got [None, None] of type 'list' instead. Error: Expected int32, got None of type '_Message

### ISSUE THREAD

**Issue by Jasonxu033** [Shathe/Ev-SegNet#1]
input: (?, 22, 14, 128)
input_to_copy: (?, ?, ?, 128)
Traceback (most recent call last):
  File "train_eager.py", line 111, in <module>
    init_model(model, input_shape=(batch_size, width, height, channels))
  File "/home/zhaodi/packages/Ev-SegNet-master/utils/utils.py", line 54, in init_model
    model._set_inputs(np.zeros(input_shape))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 2776, in _set_inputs
    outputs = self(inputs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 629, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/autograph/impl/api.py", line 149, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))
TypeError: in converted code:

    /home/zhaodi/packages/Ev-SegNet-master/nets/Network.py:172 call *
        x += reshape_into(self.adap_encoder_2(outputs[1], training=training), x)  # 512
    /home/zhaodi/packages/Ev-SegNet-master/nets/Network.py:291 reshape_into *
        return tf.image.resize_bilinear(inputs, [input_to_copy.get_shape()[1].value,
    /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/image_ops_impl.py:3374 resize_bilinear
        name=name)
    /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_image_ops.py:3333 resize_bilinear
        half_pixel_centers=half_pixel_centers, name=name)
    /usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py:536 _apply_op_helper
        repr(values), type(values).__name__, err))

    TypeError: Expected int32 passed to parameter 'size' of op 'ResizeBilinear', got [None, None] of type 'list' instead. Error: Expected int32, got None of type '_Message
' instead.

Could you please give some advise about this problem？Thanks

**Comment by DaliaHareb** [comment]
Have you found the answer to your question please ?

**Comment by ShristiDasBiswas** [comment]
Hi! Please share the solution to this issue! Thanks in advance.

**Comment by DaliaHareb** [comment]
> Hi! Please share the solution to this issue! Thanks in advance.

I could resolve the problem by using python2.7 and tensorflow version ==1.11.0. Hope it's gonna work for you.

Good luck.

**Comment by ShristiDasBiswas** [comment]
> > Hi! Please share the solution to this issue! Thanks in advance.
> 
> I could resolve the problem by using python2.7 and tensorflow version ==1.11.0. Hope it's gonna work for you.
> 
> Good luck.

Hi! Thank you! Could you please share your environment file?
